name: Docker build & publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
env:
  IMAGE_NAME: plutojl
  BINDER_IMAGE_NAME: plutojl-binder

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
    
      - name: Push plutojl to DockerHub
        uses: docker/build-push-action@v1.1.1
        with:
          username: shashankpv
          password: ${{ secrets.DOCKER_PAT }}
          path: ./docker/precompiled
          repository: plutojl 
          dockerfile: ./docker/precompiled/Dockerfile 

      - name: Push plutojl-binder to DockerHub
        uses: docker/build-push-action@v1.1.1
        with:
          username: shashankpv
          password: ${{ secrets.DOCKER_PAT }}
          path: ./docker/binder
          repository: plutojl-binder
          dockerfile: ./docker/binder/Dockerfile 
